### ISSUE TITLE
subclasses

### ISSUE THREAD

**Issue by cambridgemike** [goncalossilva/deep_copy#1]
Awesome plugin (really surprised there isn't more support for this out there). 

I tried it out with rails 3, everything seems to work fine.

There is one bug (and it probably applies to 2.x as well), the deep_copy chokes when you have an association that is a sub class. For instance:

class foo
  has_many :car
end

class car
end

class baz < car
end

my_foo = Foo.new
my_foo.cars << Baz.new
my_foo.save

my_foo.deep_copy

this seems to die

Cheers,
mike

**Comment by goncalossilva** [comment]
Just tested your example and it works perfectly with Rails 2.3.11. I'm gonna
give 3.0.7 a look :)

**Comment by goncalossilva** [comment]
Weird — just tested it and everything worked. Here's the app I used for testing: http://feupload.fe.up.pt/get/Xa4c53ghy0DTKkW

Care to give me a non-working example? Thanks.

**Comment by cambridgemike** [comment]
Hey sorry about that. I tried to extract the example from my app, but didn't test it (bad on me). I'll take another look at it and see if I can't figure out what went wrong. I'll let you know what I find out. 

Cheers,

-mike

**Comment by goncalossilva** [comment]
I'd appreciate that. Thanks.
